version: '3.8'
services:
  judge:
    container_name: dmoj_judge_server
    image: zydhanlinnar11/dmoj-judge-server
    restart: always
    volumes:
      - ./problems/:/problems
    cap_add:
      - SYS_PTRACE
    command: dmoj -c /judge-runtime-paths.yml -p 9999 sch-npc-junior.zydhan.xyz
