version: '3.8'
services:
  judge:
    build:
      context: .
      dockerfile: ./judge/Dockerfile
    container_name: dmoj_judge_server
    image: zydhanlinnar11/dmoj-judge-server
    restart: always
    volumes:
      - ./problems/:/problems
      - ./judge/:/config
    cap_add:
      - SYS_PTRACE
    command: dmoj -c /judge-runtime-paths.yml -p 9999 sch-npc-junior.zydhan.xyz
    env_file: [judge/judge.env]
