version: '3.8'
services:
  judge:
    build:
      context: .
      dockerfile: ./judge/Dockerfile
    container_name: dmoj_judge_server
    image: zydhanlinnar11/dmoj-judge-server
    restart: unless-stopped
    privileged: true
    cap_add: 
      - CAP_SYS_ADMIN
    volumes:
      - ./judge/:/config
    cap_add:
      - SYS_PTRACE
    env_file: [judge/judge.env]
